/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the authenticated tenant
         * @description Returns the tenant identified by the bearer token, including its SES alignment status.
         */
        get: operations["getCurrentTenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List domains */
        get: operations["listDomains"];
        put?: never;
        /** Add a domain */
        post: operations["createDomain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/domains/{domain}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: components["parameters"]["DomainPath"];
            };
            cookie?: never;
        };
        /** Get a domain */
        get: operations["getDomain"];
        put?: never;
        post?: never;
        /** Remove a domain */
        delete: operations["deleteDomain"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/domains/{domain}/dns-records": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: components["parameters"]["DomainPath"];
            };
            cookie?: never;
        };
        /**
         * Get required DNS records
         * @description Returns the DNS records the customer must publish. For delegated domains (`sesAlignment.delegatedSubdomain` set) this is a single NS record at the apex; QPost manages SPF/DKIM inside the delegated zone automatically. For legacy apex-provisioned domains this returns the full SPF/DKIM/tracking record set.
         */
        get: operations["getDomainDnsRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/domains/{domain}/tracking": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: components["parameters"]["DomainPath"];
            };
            cookie?: never;
        };
        /** Get open/click tracking settings */
        get: operations["getDomainTracking"];
        /** Update open/click tracking settings */
        put: operations["updateDomainTracking"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/domains/{domain}/delegation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: components["parameters"]["DomainPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Migrate a domain onto a delegated subdomain
         * @description Moves a legacy apex-provisioned domain onto the `qp.<domain>` delegated-subdomain model (one Route 53 hosted zone per domain, NS-delegated from the customer's apex). Idempotent; safe to call again to re-fetch nameservers.
         */
        post: operations["migrateDomainDelegation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/domains/{domain}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: components["parameters"]["DomainPath"];
            };
            cookie?: never;
        };
        /**
         * Get domain sending statistics
         * @description All-time event counts by type for this domain. Backed directly by `EventService.statsSummary` (a `GROUP BY event_type` count) — there is no date-range or resolution breakdown in the current implementation, so this endpoint intentionally has no query parameters. A time-series version (start/end/resolution) is plausible future work, not modeled here since it doesn't exist yet.
         */
        get: operations["getDomainStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/domains/{domain}/ghost-config": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: components["parameters"]["DomainPath"];
            };
            cookie?: never;
        };
        /** Get a ready-to-use Ghost CMS bulk-email config snippet */
        get: operations["getGhostConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a message
         * @description Native JSON equivalent of the Mailgun-compatible `POST /v3/{domain}/messages`. `domain` is optional in the body — if omitted, it's inferred from the `from` address — since the native surface doesn't require a domain path segment.
         */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/mime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a raw MIME message
         * @description Native equivalent of `POST /v3/{domain}/messages.mime`.
         */
        post: operations["sendMimeMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppressions/{listType}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listType: components["parameters"]["SuppressionListType"];
            };
            cookie?: never;
        };
        /** List suppressed addresses */
        get: operations["listSuppressions"];
        put?: never;
        /** Add a single suppressed address */
        post: operations["addSuppression"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppressions/{listType}/import": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listType: components["parameters"]["SuppressionListType"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk-import suppressed addresses */
        post: operations["importSuppressions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppressions/{listType}/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listType: components["parameters"]["SuppressionListType"];
                address: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a suppressed address */
        delete: operations["deleteSuppression"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ip-pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List IP pools */
        get: operations["listIpPools"];
        put?: never;
        /** Create an IP pool */
        post: operations["createIpPool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ip-pools/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an IP pool */
        delete: operations["deleteIpPool"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ip-pools/{name}/ips": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add an IP to a pool */
        post: operations["addIpToPool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all dedicated IPs */
        get: operations["listIps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get account sending status */
        get: operations["getAccountStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
            message?: string | null;
        };
        /** @description One freeform, forward-compatibility extension entry. See the versioning section above. */
        NameValuePair: {
            name: string;
            value: string | null;
        };
        Paging: {
            page?: number;
            limit?: number;
            /** @description Null when the total isn't cheaply computable; use has_more to drive further paging regardless. */
            total_items?: number | null;
            has_more?: boolean;
        };
        /** @description The authenticated tenant. `sesAlignment` reflects the target tenant=domain=identity=SES-tenant model described in docs/ses-resource-model.md; see this spec's top-level description for status. */
        Tenant: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @description Stable tenant slug used to key SES-side resources (`qpost-<slug>`). New field, not present on `Tenant` today — introduced by this spec per docs/ses-resource-model.md's recommendation. */
            slug?: string | null;
            rateLimitRps?: number;
            rateLimitBurst?: number;
            sesAlignment?: components["schemas"]["TenantSesAlignment"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            metadata?: components["schemas"]["NameValuePair"][];
        };
        TenantSesAlignment: {
            /**
             * @description not_provisioned until the sesv2 tenant-management migration ships.
             * @enum {string}
             */
            status?: "not_provisioned" | "provisioning" | "active" | "paused";
            /** @description e.g. qpost-<slug> */
            sesTenantName?: string | null;
            /** @description One configuration set per tenant, shared by all of the tenant's domains. */
            sesConfigurationSetName?: string | null;
        };
        CreateDomainRequest: {
            name: string;
        };
        Domain: {
            name?: string;
            /** @enum {string} */
            status?: "pending" | "verified" | "failed";
            /** @constant */
            type?: "custom";
            wildcard?: boolean;
            trackingCname?: string | null;
            sesAlignment?: components["schemas"]["DomainSesAlignment"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            verifiedAt?: string | null;
            metadata?: components["schemas"]["NameValuePair"][];
        };
        /** @description How this domain maps to an SES identity, and whether it's associated to its tenant's SES tenant. */
        DomainSesAlignment: {
            /** @description e.g. qp.example.com — null for legacy apex-provisioned domains. */
            delegatedSubdomain?: string | null;
            /** @description The SES identity name backing this domain (delegatedSubdomain, or the apex domain for legacy domains). */
            sesIdentity?: string | null;
            route53ZoneId?: string | null;
            /** @description Whether this identity is associated to the owning tenant's SES tenant. False until that migration ships. */
            associatedToSesTenant?: boolean;
        };
        DnsRecord: {
            /** @enum {string} */
            recordType?: "NS" | "TXT" | "CNAME" | "MX";
            name?: string;
            value?: string;
            ttl?: number;
        };
        DnsRecordSet: {
            domain?: string;
            delegated?: boolean;
            records?: components["schemas"]["DnsRecord"][];
        };
        TrackingSettings: {
            opens?: boolean;
            clicks?: boolean;
        };
        /** @description All-time event counts by type, e.g. delivered=120, opened=45, bounced=2. */
        DomainStats: {
            domain?: string;
            /** @description Keyed by event type (see EventType); only types with at least one event appear. */
            counts?: {
                [key: string]: number;
            };
        };
        GhostConfig: {
            domain?: string;
            /** @enum {string} */
            state?: "active" | "unverified";
            baseUrl?: string;
            /** @description Placeholder — never echoes the real key. */
            apiKey?: string;
            yaml?: string;
            instructions?: string[];
        };
        /** @description Native JSON equivalent of the Mailgun form fields handled by MailgunMessageParser. Structured fields below (tags, userVariables, etc.) are unchanged from the Mailgun surface's semantics — `metadata` is an additional escape hatch, not a replacement for any of them. */
        SendMessageRequest: {
            /** @description Optional; inferred from `from` if omitted. */
            domain?: string | null;
            /** Format: email */
            from: string;
            to: string[];
            cc?: string[];
            bcc?: string[];
            replyTo?: string[];
            subject: string;
            html?: string | null;
            text?: string | null;
            tags?: string[];
            /** @default false */
            testMode: boolean;
            trackingOpens?: boolean | null;
            trackingClicks?: boolean | null;
            /** @description Keyed by recipient address, for %recipient.field% personalization. */
            recipientVariables?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            } | null;
            /** @description Custom variables (Mailgun's v: prefix), echoed back on events as user-variables. */
            userVariables?: {
                [key: string]: string;
            };
            campaignId?: string | null;
            /** Format: date-time */
            scheduledFor?: string | null;
            metadata?: components["schemas"]["NameValuePair"][];
        };
        SendMimeMessageRequest: {
            /**
             * Format: binary
             * @description Raw RFC 822 MIME message.
             */
            message: string;
            to: string[];
        };
        SendMessageResponse: {
            id?: string;
            /** @constant */
            message?: "Queued. Thank you.";
            metadata?: components["schemas"]["NameValuePair"][];
        };
        /** @enum {string} */
        EventType: "delivered" | "opened" | "clicked" | "bounced" | "complained" | "failed" | "accepted" | "rejected" | "unsubscribed";
        GeoLocation: {
            country?: string | null;
            region?: string | null;
            city?: string | null;
        };
        ClientInfo: {
            clientOs?: string | null;
            clientName?: string | null;
            clientType?: string | null;
            deviceType?: string | null;
            userAgent?: string | null;
        };
        /** @description Present only on failed events. */
        DeliveryStatus: {
            code?: number | null;
            message?: string | null;
            description?: string | null;
        };
        Event: {
            id?: string;
            event?: components["schemas"]["EventType"];
            /** @description Epoch seconds with millisecond fraction. */
            timestamp?: number;
            /** Format: email */
            recipient?: string;
            /** @enum {string|null} */
            severity?: "permanent" | "temporary" | null;
            reason?: string | null;
            /** @description Present on click events. */
            url?: string | null;
            deliveryStatus?: components["schemas"]["DeliveryStatus"] | null;
            messageId?: string;
            userVariables?: {
                [key: string]: string;
            };
            geolocation?: components["schemas"]["GeoLocation"];
            clientInfo?: components["schemas"]["ClientInfo"];
            metadata?: components["schemas"]["NameValuePair"][];
        };
        EventList: {
            items?: components["schemas"]["Event"][];
            paging?: components["schemas"]["Paging"];
        };
        DomainList: {
            items?: components["schemas"]["Domain"][];
            paging?: components["schemas"]["Paging"];
        };
        CreateSuppressionRequest: {
            /** Format: email */
            address: string;
            /** @description e.g. an SMTP status/reason, for bounce imports. */
            error?: string | null;
        };
        Suppression: {
            /** Format: email */
            address?: string;
            /** @enum {string} */
            listType?: "bounces" | "complaints" | "unsubscribes";
            reason?: string | null;
            /** Format: date-time */
            createdAt?: string;
            metadata?: components["schemas"]["NameValuePair"][];
        };
        SuppressionList: {
            items?: components["schemas"]["Suppression"][];
            paging?: components["schemas"]["Paging"];
        };
        IpPool: {
            name?: string;
            ips?: string[];
        };
        AccountStatus: {
            sendingEnabled?: boolean;
            max24HourSend?: number;
            maxSendRate?: number;
            sentLast24Hours?: number;
            reputationStatus?: string;
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        DomainPath: string;
        Page: number;
        Limit: number;
        SuppressionListType: "bounces" | "complaints" | "unsubscribes";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current tenant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listDomains: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of domains */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createDomain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDomainRequest"];
            };
        };
        responses: {
            /** @description Domain created (pending verification) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Domain"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Domain already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getDomain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: components["parameters"]["DomainPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The domain */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Domain"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteDomain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: components["parameters"]["DomainPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Domain removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getDomainDnsRecords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: components["parameters"]["DomainPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DNS records required for this domain */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsRecordSet"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getDomainTracking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: components["parameters"]["DomainPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tracking settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateDomainTracking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: components["parameters"]["DomainPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackingSettings"];
            };
        };
        responses: {
            /** @description Updated tracking settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingSettings"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    migrateDomainDelegation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: components["parameters"]["DomainPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delegation migration started or already complete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Domain"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getDomainStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: components["parameters"]["DomainPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All-time event counts for the domain */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainStats"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getGhostConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: components["parameters"]["DomainPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ghost configuration snippet */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GhostConfig"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Message queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendMessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    sendMimeMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["SendMimeMessageRequest"];
            };
        };
        responses: {
            /** @description Message queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendMessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listEvents: {
        parameters: {
            query: {
                domain: string;
                /** @description Filter to a single event type */
                event?: components["schemas"]["EventType"];
                recipient?: string;
                message_id?: string;
                page?: components["parameters"]["Page"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listSuppressions: {
        parameters: {
            query: {
                domain: string;
                page?: components["parameters"]["Page"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                listType: components["parameters"]["SuppressionListType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of suppressions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuppressionList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    addSuppression: {
        parameters: {
            query: {
                domain: string;
            };
            header?: never;
            path: {
                listType: components["parameters"]["SuppressionListType"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSuppressionRequest"];
            };
        };
        responses: {
            /** @description Suppression added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suppression"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    importSuppressions: {
        parameters: {
            query: {
                domain: string;
            };
            header?: never;
            path: {
                listType: components["parameters"]["SuppressionListType"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSuppressionRequest"][];
            };
        };
        responses: {
            /** @description Import result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Number of addresses imported */
                        imported?: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteSuppression: {
        parameters: {
            query: {
                domain: string;
            };
            header?: never;
            path: {
                listType: components["parameters"]["SuppressionListType"];
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Suppression removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listIpPools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description IP pools */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpPool"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createIpPool: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description IP pool created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpPool"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteIpPool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description IP pool deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    addIpToPool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: ipv4 */
                    ip: string;
                };
            };
        };
        responses: {
            /** @description IP added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpPool"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listIps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dedicated IPs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: ipv4 */
                        ip?: string;
                        pool?: string;
                    }[];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAccountStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account sending status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
